language: node_js

before_install:
    - nvm install 8.9.4

cache: npm

script: echo "npm test temporarily disabled"

notifications:
    email:
      recipients:
        - bhanuagrawal2018@gmail.com
      on_success: always
      on_failure: always
